In [1]:
import numpy as np

In [2]:
a = np.random.randint(0, 100, (2, 3, 5))

In [3]:
a

array([[[81, 75, 46, 44, 62],
        [ 1, 99, 54, 42, 46],
        [11, 14, 17, 20, 55]],

       [[27, 27, 69,  6, 11],
        [84, 93, 93, 45, 97],
        [16, 40, 65, 88, 27]]])

In [4]:
b = np.ones((5, 2, 3))

In [5]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [6]:
a.size

30

In [7]:
b.size

30

In [8]:
a.shape

(2, 3, 5)

In [9]:
b.shape

(5, 2, 3)

In [10]:
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [11]:
np.array_equal(a, b)

False

In [12]:
a

array([[[81, 75, 46, 44, 62],
        [ 1, 99, 54, 42, 46],
        [11, 14, 17, 20, 55]],

       [[27, 27, 69,  6, 11],
        [84, 93, 93, 45, 97],
        [16, 40, 65, 88, 27]]])

In [13]:
c = b.transpose((1, 2, 0))

In [14]:
d = np.add(a, c)

In [15]:
d.max()

100.0

In [16]:
f = np.empty([2, 3, 5])

In [17]:
f

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [18]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print( d_max, d_min, d_mean)
    

100.0 2.0 49.5


In [23]:
f[d==d_mean]=50
print (f)

TypeError: 'int' object does not support item assignment

In [54]:
d[f.any() > d_min and f.any() < d_mean] = 25
f[d.any() > d_mean and d.any() < d_max] = 75
f[d.any() == d_mean] = 50
f[d.any() == d_min] = 0
f[d.any() == d_max] = 100
print(f)

[[[  8.  34.   4.  98.  58.]
  [ 42.  66.  36.  25.  70.]
  [ 79.  64.  69.  97.  53.]]

 [[  7.  81.  58.  81.  69.]
  [100.  62.  11.  22.  53.]
  [ 63.  26.  30.  32.  36.]]]


TypeError: 'int' object does not support item assignment